<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="6fbaf507-9ce5-4e73-ab1d-c02dbc5d63b8" name="dwilloug@PHINEAS 2012-11-03 22:31:03" runUser="USERS\dwilloug" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="33500a2c-091e-4f9b-a348-a6603a00d679">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="dwilloug_PHINEAS 2012-11-03 22_31_03">
      <DeploymentItem filename="D:\Users\dwilloug\PS7\PS7\bin\Debug\PS7.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2012-11-03T22:31:03.4876334-06:00" queuing="2012-11-03T22:31:03.5626334-06:00" start="2012-11-03T22:31:03.5786334-06:00" finish="2012-11-03T22:32:57.5166334-06:00" />
  <ResultSummary outcome="Error">
    <Counters total="1" executed="1" error="0" failed="0" timeout="0" aborted="1" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="PHINEAS" outcome="Error" timestamp="2012-11-03T22:32:57.4056334-06:00">
        <Text>One of the background threads threw exception: 
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Send(Byte[] buffer)
   at CustomNetworking.StringSocket.sendingLoop() in D:\Users\dwilloug\PS7\PS7\StringSocket.cs:line 159
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</Text>
      </RunInfo>
      <RunInfo computerName="PHINEAS" outcome="Error" timestamp="2012-11-03T22:32:57.4056334-06:00">
        <Text>One of the background threads threw exception: 
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError&amp; errorCode)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at CustomNetworking.StringSocket.receivingLoop() in D:\Users\dwilloug\PS7\PS7\StringSocket.cs:line 222
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Test4" storage="d:\users\dwilloug\ps7\stringsockettester\bin\debug\stringsockettester.dll" id="b7b6e2f2-633b-58fd-3f0b-561c3dd6d4b0">
      <Execution id="d5ca83d2-7b17-48d3-a7b3-940950a414c7" />
      <TestMethod codeBase="D:\Users\dwilloug\PS7\StringSocketTester\bin\Debug\StringSocketTester.dll" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="StringSocketTester.StringSocketTest, StringSocketTester" name="Test4" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="b7b6e2f2-633b-58fd-3f0b-561c3dd6d4b0" executionId="d5ca83d2-7b17-48d3-a7b3-940950a414c7" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="d5ca83d2-7b17-48d3-a7b3-940950a414c7" testId="b7b6e2f2-633b-58fd-3f0b-561c3dd6d4b0" testName="Test4" computerName="PHINEAS" duration="00:01:48.7930000" startTime="2012-11-03T22:31:03.5886334-06:00" endTime="2012-11-03T22:32:52.3816334-06:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Aborted" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="d5ca83d2-7b17-48d3-a7b3-940950a414c7">
      <Output>
        <ErrorInfo>
          <Message>User aborted test run.</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>